### ISSUE TITLE
已经接入switch的机器A，做成镜像恢复成机器B，B机器接入switch无法和A共存，会发生交替接入的情况

### ISSUE THREAD

**Issue by myzzzqqwa** [luscis/openlan#20]
<img width="399" alt="image" src="https://github.com/luscis/openlan/assets/24540630/eb12f59a-0c8e-4050-80c8-62cdeded9ca3">

次地址已经与A机器做过区分

**Comment by danieldin95** [comment]
确认使用的不同账户？
