### ISSUE TITLE
修改默认端口后 openlan us ls 报错，还是访问的默认端口

### ISSUE THREAD

**Issue by myzzzqqwa** [luscis/openlan#26]
![Uploading 企业微信截图_8108f7b3-00a9-4979-a1e5-a4ea50ebdf10.png…]()

**Comment by myzzzqqwa** [comment]
[root@olcom-openlan-switch center]# openlan us ls
2024/01/06 05:29:16 Get "https://localhost:10000/api/user": dial tcp [::1]:10000: connect: connection refused

**Comment by danieldin95** [comment]
使用自定义路径：
export URL="https://localhost:10012/"
