### ISSUE TITLE
支持rocky linux

### ISSUE THREAD

**Issue by mynicolas** [luscis/openlan#29]
使用安装教程无法在rocky linux 8.9上安装

**Comment by danieldin95** [comment]
提供下错误输出

**Comment by mynicolas** [comment]
[root@ops-testus ~]# ./openlan-CentOS7.8.2003-v24.01.01.x86_64.bin
+ tmp=
+ installer=./openlan-CentOS7.8.2003-v24.01.01.x86_64.bin
++ grep -a -n '__ARCHIVE_BELOW__:$' ./openlan-CentOS7.8.2003-v24.01.01.x86_64.bin
++ cut -f1 -d:
+ archive=67
+ download
++ mktemp -d
+ tmp=/tmp/tmp.mLP3cuAoB4
+ tail -n +68 ./openlan-CentOS7.8.2003-v24.01.01.x86_64.bin
+ gzip -dc -
+ tar -xf - -C /tmp/tmp.mLP3cuAoB4
+ requires
+ type yum
+ yum install -y xl2tpd openssl net-tools iptables iputils openvpn openvswitch dnsmasq bridge-utils iperf3 tcpdump ipset
Last metadata expiration check: 1:09:47 ago on Fri 12 Jan 2024 10:15:10 AM UTC.
Package openssl-1:1.1.1k-12.el8_9.x86_64 is already installed.
Package iptables-1.8.5-9.el8.x86_64 is already installed.
Package iputils-20180629-11.el8.x86_64 is already installed.
No match for argument: openvswitch
Error: Unable to find a match: openvswitch

**Comment by danieldin95** [comment]
你可以google下how to install openvswitch for rocky，或者使用docker去启动openlan参考

**Comment by mynicolas** [comment]
[root@ops-testus openlan]# docker compose ps
NAME                     IMAGE                             COMMAND                                                                      SERVICE        CREATED         STATUS                                    PORTS
openlan-confd-1          luscis/openlan:v24.01.01.x86_64   "/var/openlan/script/confd.sh start"                                         confd          8 seconds ago   Up 7 seconds                              0.0.0.0:10000->10000/tcp, :::10000->10000/tcp, 0.0.0.0:10002->10002/tcp, :::10002->10002/tcp
openlan-ovs-vswitchd-1   luscis/openlan:v24.01.01.x86_64   "/var/openlan/script/ovs-vswitchd.sh start"                                  ovs-vswitchd   8 seconds ago   Up 7 seconds

openlan-ovsdb-server-1   luscis/openlan:v24.01.01.x86_64   "/var/openlan/script/ovsdb-server.sh start"                                  ovsdb-server   8 seconds ago   Up 7 seconds

openlan-proxy-1          luscis/openlan:v24.01.01.x86_64   "/usr/bin/openlan-proxy -conf /etc/openlan/proxy.json -log:file /dev/null"   proxy          8 seconds ago   Up 7 seconds

openlan-switch-1         luscis/openlan:v24.01.01.x86_64   "/var/openlan/script/switch.sh start"                                        switch         8 seconds ago   Restarting (255) Less than a second ago
openlan-task-1           luscis/openlan:v24.01.01.x86_64   "/var/openlan/script/task.sh"                                                task           8 seconds ago   Up 7 seconds

[root@ops-testus openlan]# docker logs openlan-switch-1
+ sysctl -p /etc/sysctl.d/90-openlan.conf
net.ipv4.ip_forward = 1
sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-ip6tables: No such file or directory
sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-iptables: No such file or directory
sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-arptables: No such file or directory

**Comment by mynicolas** [comment]
[root@ops-testus openlan]# ls /proc/sys/net/bridge/bridge-nf-call-ip6tables
/proc/sys/net/bridge/bridge-nf-call-ip6tables
[root@ops-testus openlan]# ls /proc/sys/net/bridge/bridge-nf-call-iptables
/proc/sys/net/bridge/bridge-nf-call-iptables

**Comment by mynicolas** [comment]
都改成network: host可以启动了。
point怎么用docker启动？

**Comment by danieldin95** [comment]
像这样
```
[root@switch-sh ~]# cd network
[root@switch-sh ~]# cat > private.json <<EOF
{
  "name": "private",
  "bridge": {
    "name": "br-em2",
    "address": "192.168.1.88/24"
  },
  "subnet": {
    "end": "192.168.1.150",
    "netmask": "255.255.255.0",
    "start": "192.168.1.100"
  },
  "openvpn": {
    "listen": "0.0.0.0:1188",
    "subnet": "172.32.88.0/24"
  },
  "links": [
    {
      "connection": "address-of-switch-nj",
      "password": "get-it-from-switch-nj",
      "username": "admin",
      "crypt": { 
         "secret": "f367aa429ed2" 
      }
    }
  ]
}
EOF
[root@switch-sh ~]# openlan cfg co
[root@switch-sh ~]# systemctl restart openlan-switch
```
