### ISSUE TITLE
support speed limit for openvpn client.

### ISSUE THREAD

**Issue by danieldin95** [luscis/openlan#38]

**Comment by danieldin95** [comment]
```
iptables -N daniel-RL
iptables -A daniel-RL -m limit --limit 1mbit/s -j ACCEPT
iptables -A daniel-RL -j DROP
iptables -A FORWARD -i tun1025 -s 169.254.1.100 -j daniel-RL

**Comment by Teddy-Zhu** [comment]
![image](https://github.com/luscis/openlan/assets/9956097/d8838d30-84bc-48de-a724-57da127820a6)

**Comment by danieldin95** [comment]
@Teddy-Zhu please `iptables -S` to show you qos rules.

**Comment by Teddy-Zhu** [comment]
![image](https://github.com/luscis/openlan/assets/9956097/424e4d66-f7f1-4e1a-96a2-7901f5411cb3)

**Comment by danieldin95** [comment]
OK! Please send a pull request for your patch.

**Comment by danieldin95** [comment]
Please refer to ztrust to design your jump chain

<img width="1059" alt="image" src="https://github.com/luscis/openlan/assets/12085357/7391297d-6b4a-4839-81f2-21c6b2ba6205">
