### ISSUE TITLE
OpenVPN 客户端启用服务端推送的 DNS 配置

### ISSUE THREAD

**Issue by fanzhengweiwudi** [luscis/openlan#70]
无法正常使用dns 私有路由

**Comment by fanzhengweiwudi** [comment]
![8a52d1542adf57c306ca21f2cde4f65](https://github.com/user-attachments/assets/bc3185a3-208b-4552-a58f-e0ae6605dbf9)

**Comment by danieldin95** [comment]
部分win系统虽然dns下发成功，但是还会依然使用之前网卡的dns配置，你可以手动修改他。
